kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pi4api-k8s-poc.yml
- pingaccess/pa_configmap.yaml
- pingaccess/pingaccess.yaml
- pingfederate/pf_configmap.yaml
- pingfederate/pingfederate.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: mongo
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
            - name: regsecret
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dustinkelly/pingidentity:mongo-4.2
  - target:
      group: apps
      version: v1 
      kind: StatefulSet 
      name: abs 
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
            - name: regsecret
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dustinkelly/pingidentity:abs-4.3
  - target:
      group: apps
      version: v1 
      kind: StatefulSet 
      name: ase 
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
            - name: regsecret
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dustinkelly/pingidentity:ase-4.3
      - op: replace 
        path: /spec/template/spec/containers/0/env/1/value
        value: "sideband"
      - op: add 
        path: /spec/template/spec/containers/0/env/9
        value: 
            name: "ENABLE_SIDEBAND_AUTHENTICATION"
      - op: add
        path: /spec/template/spec/containers/0/env/9/value
        value: "true"
  - target:
      group: apps
      version: v1 
      kind: StatefulSet 
      name: dashboard 
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
            - name: regsecret
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dustinkelly/pingidentity:dashboard-4.3
      - op: replace 
        path: /spec/template/spec/containers/0/env/14/value
        value: "sideband"
      - op: add 
        path: /spec/template/spec/containers/0/env/15
        value: 
            name: "DISCOVERY_SOURCE"
      - op: add
        path: /spec/template/spec/containers/0/env/15/value
        value: "pingaccess"
      - op: add 
        path: /spec/template/spec/containers/0/env/16
        value: 
            name: "PINGACCESS_URL"
      - op: add
        path: /spec/template/spec/containers/0/env/16/value
        value: "https://pingaccess-admin-ping-cloud-devops-eks-.ping-devops.com/"
      - op: add 
        path: /spec/template/spec/containers/0/env/17
        value: 
            name: "PINGACCESS_USERNAME"
      - op: add
        path: /spec/template/spec/containers/0/env/17/value
        value: "Administrator"
      - op: add 
        path: /spec/template/spec/containers/0/env/18
        value: 
            name: "PINGACCESS_PASSWORD"
      - op: add
        path: /spec/template/spec/containers/0/env/18/value
        value: "2SideBand"
      - op: add 
        path: /spec/template/spec/containers/0/env/19
        value: 
            name: "DISCOVERY_MODE"
      - op: add
        path: /spec/template/spec/containers/0/env/19/value
        value: "manual"
      - op: add 
        path: /spec/template/spec/containers/0/env/20
        value: 
            name: "DISCOVERY_MODE_AUTO_DELETE_NON_DISCOVERED_APIS"
      - op: add
        path: /spec/template/spec/containers/0/env/20/value
        value: "false"
  - target:
      group: 
      version: v1 
      kind: Service 
      name: abs-external-service 
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32080
      - op: replace
        path: /spec/ports/1/nodePort
        value: 32090
  - target:
      group: 
      version: v1 
      kind: Service 
      name: ase-external-service 
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32000
      - op: replace
        path: /spec/ports/1/nodePort
        value: 32443
  - target:
      group: 
      version: v1 
      kind: Service 
      name: dashboard-external-service 
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32030
  - target:
      group: 
      version: v1 
      kind: ConfigMap 
      name: abs-license
    patch: |-
      - op: replace
        path: /data
        value: 
          PingIntelligence.lic: |-
            ID=00092294
            Module=ABS
            MaxTransactionsPerMonth=100000
            Product=PingIntelligence
            Version=4.3
            EnforcementType=3
            Tier=Subscription
            IssueDate=2020-11-20
            ExpirationDate=2020-12-20
            DeploymentMethod=Traditional
            Organization=Ping Identity Corporation
            SignCode=FF07
            Signature=302C02142339F293D28B15EE78A1223E9A6CC0AD999E8C7A02144139A3C17C3317BDD8928A3C0742C5AAE454C6FA
            
  - target:
      group: 
      version: v1 
      kind: ConfigMap 
      name: ase-license
    patch: |-
      - op: replace
        path: /data
        value: 
          PingIntelligence.lic: |-
            ID=00092295
            Module=ASE
            MaxTransactionsPerMonth=100000
            Product=PingIntelligence
            Version=4.3
            EnforcementType=3
            Tier=Subscription
            IssueDate=2020-11-20
            ExpirationDate=2020-12-20
            DeploymentMethod=Traditional
            Organization=Ping Identity Corporation
            SignCode=FF07
            Signature=302C0214235E85950AA10B2783FF69E6D60463EEDF85AD8002142EBFDFD42074E5D9C3ED97A9F61CCE9D9269BB18