apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingaccess
  SERVER_PROFILE_URL: https://www.github.com/jacenb/pingidentity-server-profiles.git
  PING_IDENTITY_PASSWORD: "2SideBand"
  PING_IDENTITY_K8S_NAMESPACE: ${PING_IDENTITY_K8S_NAMESPACE}
  PA_LOG_LEVEL: "DEBUG"
kind: ConfigMap
metadata:
  labels:
    role: pingaccess
  name: pingaccess-environment-variables