apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingfederate
  SERVER_PROFILE_URL: https://www.github.com/jacenb/pingidentity-server-profiles.git
  PING_IDENTITY_K8S_NAMESPACE: ${PING_IDENTITY_K8S_NAMESPACE}
kind: ConfigMap
metadata:
  labels:
    role: pingfederate
  name: pingfederate-environment-variables